#!/bin/bash
##
## docker-entrypoint.sh — FreeSWITCH container startup script
##
## Responsibilities:
##   1. Validate required environment variables
##   2. Generate /etc/freeswitch/vars.xml from vars.xml.tpl using envsubst
##   3. Write event_socket.conf.xml with the correct ESL password
##   4. Exec FreeSWITCH in foreground (PID 1)
##
## Environment variables consumed (see .env.example at project root):
##
##   Required in production (injected from AWS Secrets Manager):
##     VOIP_INTERNAL_TOKEN     — JWT shared secret for Lua → FastAPI auth
##     VOXBONE_USERNAME        — Voxbone SIP trunk username
##     VOXBONE_PASSWORD        — Voxbone SIP trunk password
##     FS_ESL_PASSWORD         — FreeSWITCH ESL password (shared with billing worker)
##
##   Optional (have safe defaults for local dev):
##     VOIP_API_BASE_URL       — FastAPI base URL (default: http://api:8000)
##     VOXBONE_REALM           — Voxbone SIP realm   (default: sip.voxbone.com)
##     VOXBONE_PROXY           — Voxbone SIP proxy   (default: sip.voxbone.com)
##     VOIP_HTTP_TIMEOUT_MS    — Auth API timeout ms (default: 2000)
##     VOIP_TICK_TIMEOUT_MS    — Billing tick timeout (default: 1500)
##     VOIP_WARN_REMAINING_SEC — Credit warn threshold in seconds (default: 320)
##     VOIP_BEEP_REMAINING_SEC — Credit beep threshold in seconds (default: 10)
##     VOIP_AUTH_ATTEMPTS      — IVR PIN retry attempts (default: 3)
##     VOIP_PIN_LENGTH         — IVR PIN length       (default: 8)
##     VOIP_DTMF_TIMEOUT_MS    — DTMF collection timeout (default: 5000)
##     VOIP_DEFAULT_GATEWAY    — Default outbound gateway name (default: voxbone-outbound)
##
## Telecom note:
##   VOIP_INTERNAL_TOKEN and Voxbone credentials must come from AWS Secrets
##   Manager in production. Never hardcode them here or in vars.xml.tpl.

set -euo pipefail

# ── Defaults for optional vars ────────────────────────────────────────────────
: "${VOIP_API_BASE_URL:=http://api:8000}"
: "${VOIP_INTERNAL_TOKEN:=}"
: "${VOXBONE_USERNAME:=}"
: "${VOXBONE_PASSWORD:=}"
: "${VOXBONE_REALM:=sip.voxbone.com}"
: "${VOXBONE_PROXY:=sip.voxbone.com}"
: "${FS_ESL_PASSWORD:=ClueCon}"
: "${VOIP_HTTP_TIMEOUT_MS:=2000}"
: "${VOIP_TICK_TIMEOUT_MS:=1500}"
: "${VOIP_WARN_REMAINING_SEC:=320}"
: "${VOIP_BEEP_REMAINING_SEC:=10}"
: "${VOIP_AUTH_ATTEMPTS:=3}"
: "${VOIP_PIN_LENGTH:=8}"
: "${VOIP_DTMF_TIMEOUT_MS:=5000}"
: "${VOIP_DEFAULT_GATEWAY:=voxbone-outbound}"
: "${VOIP_SOUNDS_BASE:=/usr/share/freeswitch/sounds/galaxy/}"
: "${VOIP_DIGITS_BASE:=/usr/share/freeswitch/sounds/galaxy/en/digit/}"
: "${RTP_START_PORT:=16384}"
: "${RTP_END_PORT:=32768}"

# ── Warn if production secrets are missing ────────────────────────────────────
if [[ -z "${VOIP_INTERNAL_TOKEN}" ]]; then
    echo "[entrypoint] WARNING: VOIP_INTERNAL_TOKEN is empty. Lua → FastAPI calls will fail auth." >&2
fi
if [[ -z "${VOXBONE_USERNAME}" || -z "${VOXBONE_PASSWORD}" ]]; then
    echo "[entrypoint] WARNING: Voxbone credentials are empty. Outbound gateway registration will fail." >&2
fi

# ── Generate vars.xml from template ──────────────────────────────────────────
# envsubst with explicit variable list — only substitutes the listed vars.
# FreeSWITCH's own $${var} runtime references in other conf files are untouched.
TPL="/etc/freeswitch/vars.xml.tpl"
OUT="/etc/freeswitch/vars.xml"

if [[ ! -f "${TPL}" ]]; then
    echo "[entrypoint] ERROR: ${TPL} not found. Cannot generate vars.xml." >&2
    exit 1
fi

envsubst \
    '${VOIP_API_BASE_URL}
     ${VOIP_INTERNAL_TOKEN}
     ${VOXBONE_USERNAME}
     ${VOXBONE_PASSWORD}
     ${VOXBONE_REALM}
     ${VOXBONE_PROXY}
     ${VOIP_HTTP_TIMEOUT_MS}
     ${VOIP_TICK_TIMEOUT_MS}
     ${VOIP_WARN_REMAINING_SEC}
     ${VOIP_BEEP_REMAINING_SEC}
     ${VOIP_AUTH_ATTEMPTS}
     ${VOIP_PIN_LENGTH}
     ${VOIP_DTMF_TIMEOUT_MS}
     ${VOIP_DEFAULT_GATEWAY}
     ${VOIP_SOUNDS_BASE}
     ${VOIP_DIGITS_BASE}
     ${RTP_START_PORT}
     ${RTP_END_PORT}' \
    < "${TPL}" > "${OUT}"

echo "[entrypoint] vars.xml generated from template"

# ── Generate event_socket.conf.xml with the ESL password ─────────────────────
# Written dynamically so the ESL password from env never lives on disk at rest.
# acl: lan.auto covers 10.x.x.x / 172.16.x.x / 192.168.x.x (Docker bridge nets).
cat > /etc/freeswitch/autoload_configs/event_socket.conf.xml << EOF
<!--
  event_socket.conf.xml — Generated by docker-entrypoint.sh
  DO NOT EDIT — will be overwritten on container restart.
  ESL password comes from FS_ESL_PASSWORD environment variable.
-->
<configuration name="event_socket.conf" description="Event Socket">
  <settings>
    <param name="nat-map"           value="false"/>
    <param name="listen-ip"         value="0.0.0.0"/>
    <param name="listen-port"       value="8021"/>
    <param name="password"          value="${FS_ESL_PASSWORD}"/>
    <!-- Allow connections from Docker bridge and loopback only -->
    <param name="apply-inbound-acl" value="lan.auto"/>
  </settings>
</configuration>
EOF

echo "[entrypoint] event_socket.conf.xml generated"

# ── Start FreeSWITCH ──────────────────────────────────────────────────────────
# -nf      : don't fork (run in foreground, PID 1)
# -nonat   : disable NAT detection (use explicit RTP settings from vars.xml)
# "$@"     : pass any extra args from docker run / compose command override
echo "[entrypoint] Starting FreeSWITCH..."
exec freeswitch -nf -nonat "$@"
